alert("Hi,I am an another JS");
console.log("Message in the console");
let var1 = 1;
let var2 = "something";
let var3 = 45.5;
let num =6;
let num1 = 2;
let num2 = 2.4;
let a=1;
let b=5;
let c=4;
c += 5;
let x ="5" + 5 +3;
let e = 3;
let d = 1 + (e *= 2);
let f ="g";
let g = 3;
g = f;
let p =f + g;

console.log(var1);
console.log(var2);
console.log(var3);
console.log(typeof num);
console.log(num1 + num2);
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a ** b);
console.log(a / b);
console.log(a % b);
console.log(a ++);
console.log(a --);
console.log(a ++);
console.log(a ++);
console.log(a ++);
console.log(c);
console.log(x);
console.log(d);
console.log(p)